acts_as_account:
  adapter: mysql
  encoding: utf8
  database: acts_as_account
  username: root
  password:
  host: localhost

betterplace:
  adapter: mysql
  encoding: utf8
  database: betterplace_production20100222
  username: root
  password:
  host: localhost
